# Generated by Django 3.2.12 on 2022-07-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0012_remove_unique_constraint'),
        ('blog', '0002_rename_blog_image_blogdetailpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='header_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
    ]
