# Generated by Django 3.2.12 on 2022-07-10 06:07

from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0012_remove_unique_constraint'),
        ('blog', '0004_alter_blogdetailpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='header_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=mirage.fields.EncryptedTextField(max_length=250),
        ),
    ]
