# Generated by Django 3.2.12 on 2022-07-10 06:11

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220710_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=mirage.fields.EncryptedCharField(max_length=250),
        ),
    ]
