# Generated by Django 3.2.12 on 2022-07-10 06:20

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220710_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
