# Generated by Django 3.2.12 on 2022-07-10 06:21

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220710_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=mirage.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=mirage.fields.EncryptedTextField(max_length=250),
        ),
    ]
