# Generated by Django 3.2.12 on 2022-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_header_video_blogdetailpage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
