# Generated by Django 3.2.12 on 2022-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogdetailpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
