# Generated by Django 3.2.12 on 2022-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogdetailpage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='wagtailvideos.Video'),
        ),
    ]
