# Generated by Django 4.1.8 on 2023-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogdetailpage_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='links',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='link_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
