# Generated by Django 4.1.8 on 2023-05-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_delete_linkpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='links',
        ),
    ]
