# Generated by Django 4.1.8 on 2023-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_formfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='from_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subject',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='to_address',
            field=models.CharField(max_length=256),
        ),
    ]
