# Generated by Django 3.2.11 on 2022-03-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220209_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='formatted_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='latlng_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
